server.port: 8083

spring:
  application:
    name: product-catalog
  cache:
    type: redis
  mongodb:
    uri: mongodb://root:algashop@localhost:27017/product_catalog?authSource=admin
    representation.uuid: standard
  data:
    redis:
      host: localhost
      port: 6379
      password: algashop
      database: 0
      timeout: 600

algashop:
  storage:
    s3:
      bucket: algashop-images
      access-key-id: test
      secret-access-key: test
      region: us-east-1
      endpoint-override: http://localhost:4566
      presigned-url-expiration-minutes: 15
    images:
      base-url: http://localhost:4566/algashop-images

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG
    org.mongodb.driver.connection: DEBUG